dist: xenial
sudo: false

rvm:
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"

before_install:
  - gem install bundler -v '< 2'
script:
  - bundle _1.17.3_ exec rake
  - bundle _1.17.3_ exec script/sync-readme-usage
  - git diff --exit-code
