dist: xenial
sudo: false

rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"

script:
  - bundle exec rake
  - bundle exec script/sync-readme-usage
  - git diff --exit-code
